# doxygen-deploy.yml

name: doxygen-deploy

on:
  push:
    branches: [master]  # Change this to your default branch if needed ("main" instead of "master")

jobs:
  deploy-vrmodelviewer:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install Doxygen
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      # Run Doxygen with the specified Doxyfile path
      - name: Run Doxygen
        working-directory: ${{ github.workspace }}
        run: doxygen /doxygen/Doxyfile

      # Deploy HTML output from Doxygen to GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: ${{ github.workspace }}/html  # The folder containing the HTML output
